version: '3.9'

services:
  frontendserver:
    build:
      context: ./
      args:
        - MY_UID=${MY_UID}
        - MY_GID=${MY_GID}
        - PORT_FRONT=${PORT_FRONT}
    env_file:
      - .env
    volumes:
      - .:/home/appuser/devcon
    networks:
      - step250_network
    ports:
      - ${PORT_FRONT}:${PORT_FRONT}
    command: ["/bin/sh", "-c", "/home/appuser/devcon/build.sh"]
    
networks:
  step250_network:
    external: true